---
version: 4.1.1
remote_theme: LeakyAbstractions/jekyllrb-theme@latest
short_name: Jekyll Docs Theme
name: Jekyll Docs Theme • Make your documentation website look like Jekyll Docs
description: Make your documentation website look like Jekyll Docs
#url: https://jekyllrb.com
baseurl: /jekyllrb-theme
repository: https://github.com/LeakyAbstractions/jekyllrb-theme
team:
- name: Jekyll Core Team
  text: _The Jekyll Core Team's responsibility is to ensure the development
    and community around the Jekyll ecosystem thrive._
  members:
  - name: Ashwin
    user: ashmaroli
  - name: Frank
    user: DirtyF
  - name: Matt
    user: mattr-
- name: Emeritus Core Team Members
  text: _Emeritus Core Team Members were once members of Jekyll's Core Team._
  members:
  - name: Alfred
    user: alfredxing
  - name: Nick
    user: qrush
  - name: Parker
    user: parkr
  - name: Tom
    user: mojombo
timezone: America/Los_Angeles
twitter:
  username: jekyllrb
logo: "/img/logo-2x.png"
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
## API Credentials in https://capture.techulus.in/console
#screenshot_api:
#  api_key: 00000000-0000-0000-0000-000000000000
#  api_secret: 00000000-0000-0000-0000-000000000000
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
- scope:
    path: ''
  values:
    image: "/img/jekyll-og.png"
future: true
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
- ".gitignore"
- ".jekyll-cache"
- CNAME
- icomoon-selection.json
- readme.md
